FROM amazoncorretto:17-alpine

MAINTAINER "vpaklatzis@gmail.com"

COPY target/mqtt-consumer-0.0.1-SNAPSHOT.jar mqtt-consumer-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "/mqtt-consumer-0.0.1-SNAPSHOT.jar"]