FROM amazoncorretto:17-alpine

MAINTAINER "vpaklatzis@gmail.com"

COPY target/mqtt-producer-0.0.1-SNAPSHOT.jar mqtt-producer-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "/mqtt-producer-0.0.1-SNAPSHOT.jar"]